[tools]
bun = "latest"
node = "latest"

[env]
DATABASE_URL = { required = true }
NEXT_PUBLIC_ASSET_BASE_URL = { required = true }
BETTER_AUTH_SECRET = { required = true }
BETTER_AUTH_URL = { required = true }
